//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TKTEGJ_IRFEntities : DbContext
    {
        public TKTEGJ_IRFEntities()
            : base("name=TKTEGJ_IRFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dolgozo> Dolgozo { get; set; }
        public virtual DbSet<Munkakor> Munkakor { get; set; }
        public virtual DbSet<Munkavegzes> Munkavegzes { get; set; }
        public virtual DbSet<Tevekenyseg> Tevekenyseg { get; set; }
    }
}
