//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Munkavegzes
    {
        public int Id { get; set; }
        public int DolgozoId { get; set; }
        public int TevekenysegId { get; set; }
        public System.DateTime Kezdodatum { get; set; }
        public System.DateTime Vegdatum { get; set; }
        public string Megjegyzes { get; set; }
        public string Ugyfelazonosito { get; set; }
        public string Iktatoszam { get; set; }
        public Nullable<int> Iktatottoldalszam { get; set; }
        public Nullable<int> Ledolgozott { get; set; }
    
        public virtual Dolgozo Dolgozo { get; set; }
        public virtual Tevekenyseg Tevekenyseg { get; set; }
    }
}
